// 把已安装的 gzh-design skill（SKILL.md + references/*.md）打包成 worker-lib/skillAssets.ts，
// 供 Cloudflare Worker / 前端直接 import。这样部署时无需在构建机上存在 skill 目录。
//
// 本地开发或更新 skill 后运行：npm run build:assets
// 生成的 skillAssets.ts 需要提交到仓库（CI 构建只做 vite build，依赖已提交的该文件）。

import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

function findSkillDir() {
  const candidates = [
    process.env.GZH_SKILL_DIR,
    process.env.USERPROFILE && join(process.env.USERPROFILE, '.workbuddy', 'skills', 'gzh-design'),
    process.env.HOME && join(process.env.HOME, '.workbuddy', 'skills', 'gzh-design'),
    '/root/.workbuddy/skills/gzh-design',
    join(root, '..', 'gzh-design-skill'),
  ].filter(Boolean);
  for (const c of candidates) {
    if (c && existsSync(join(c, 'SKILL.md'))) return c;
  }
  return null;
}

const skillDir = findSkillDir();
if (!skillDir) {
  console.error('[build-assets] 未找到 gzh-design skill，已跳过（将沿用已提交的 worker-lib/skillAssets.ts）');
  process.exit(0);
}

const skillMd = readFileSync(join(skillDir, 'SKILL.md'), 'utf8');
const refDir = join(skillDir, 'references');
const references = {};
for (const f of readdirSync(refDir)) {
  if (f.endsWith('.md')) references[f] = readFileSync(join(refDir, f), 'utf8');
}

// 转义模板字符串里的 ` 与 ${，避免破坏生成的 TS。
function esc(s) {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

const entries = Object.entries(references)
  .map(([k, v]) => `  ${JSON.stringify(k)}: \`${esc(v)}\`,`)
  .join('\n');

const out = `// AUTO-GENERATED by scripts/build-assets.mjs — 请勿手动编辑。
// 来源：gzh-design skill (https://github.com/isjiamu/gzh-design-skill, AGPL-3.0)

export const SKILL_MD = \`${esc(skillMd)}\`;

export const REFERENCES: Record<string, string> = {
${entries}
};

export const THEME_INDEX_MD = REFERENCES['theme-index.md'] ?? '';
`;

writeFileSync(join(root, 'worker-lib', 'skillAssets.ts'), out, 'utf8');
console.log(`[build-assets] 已生成 worker-lib/skillAssets.ts（引用 ${Object.keys(references).length} 个组件库文件），来源：${skillDir}`);
